plugins {
	id 'java'
	id 'com.diffplug.spotless' version '6.23.3'
	id 'io.spring.dependency-management' version '1.1.6'
	id 'jacoco'
}

group = 'ru.mentee.power'
version = '1.0.0'

repositories {
	mavenCentral()
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

ext {
	versions = [
		spotless          : '6.23.3',
		mongodb           : '5.0.0',
		lombok           : '1.18.30',
		slf4j            : '2.0.9',
		logback          : '1.4.11',
		junit            : '5.10.0',
		assertj          : '3.24.2',
		testcontainers   : '1.20.4',
		googleJavaFormat : '1.17.0'
	]
}

dependencies {
	// MongoDB
	implementation "org.mongodb:mongodb-driver-sync:${versions.mongodb}"
	implementation "org.mongodb:bson:${versions.mongodb}"

	// Логирование
	implementation "org.slf4j:slf4j-api:${versions.slf4j}"
	implementation "ch.qos.logback:logback-classic:${versions.logback}"

	// Lombok
	compileOnly "org.projectlombok:lombok:${versions.lombok}"
	annotationProcessor "org.projectlombok:lombok:${versions.lombok}"
	testCompileOnly "org.projectlombok:lombok:${versions.lombok}"
	testAnnotationProcessor "org.projectlombok:lombok:${versions.lombok}"

	// Тестирование
	testImplementation "org.junit.jupiter:junit-jupiter:${versions.junit}"
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testImplementation "org.assertj:assertj-core:${versions.assertj}"

	// TestContainers
	testImplementation "org.testcontainers:testcontainers:${versions.testcontainers}"
	testImplementation "org.testcontainers:junit-jupiter:${versions.testcontainers}"
	testImplementation "org.testcontainers:mongodb:${versions.testcontainers}"
}

dependencyManagement {
	imports {
		mavenBom "org.testcontainers:testcontainers-bom:1.19.1"
	}
}

spotless {
	format 'misc', {
		target '*.gradle', '.gitattributes', '.gitignore'
		trimTrailingWhitespace()
		indentWithTabs()
		endWithNewline()
	}
	java {
		targetExclude('**/build/**', '**/build-generated/**')
		googleJavaFormat("${versions.googleJavaFormat}").aosp().reflowLongStrings().skipJavadocFormatting()
		formatAnnotations()
	}
}

compileJava {
	options.encoding = 'UTF-8'
}

compileTestJava {
	options.encoding = 'UTF-8'
}

tasks.withType(JavaCompile) {
	options.encoding = 'UTF-8'
}

test {
	useJUnitPlatform()
	finalizedBy jacocoTestReport
}

jacoco {
	toolVersion = '0.8.11'
}

jacocoTestReport {
	dependsOn test
	reports {
		xml.required = true
		xml.outputLocation = layout.buildDirectory.file('reports/jacoco/test/jacoco.xml')
		csv.required = false
		html.outputLocation = layout.buildDirectory.dir('reports/jacoco/test/html')
	}
}
